name: ci-building docker image
on:
  push:
    branches:
      - 'main'
jobs:
  pushing:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create Environment File
        run: |
          echo "VITE_PROD_API_URL=http://${{ secrets.PUBLIC_IP }}:3000 \
          VITE_NODE_ENV=production \
          " > .env.production.local
  
      -
        name: Build and push
        uses: docker/build-push-action@v5
        env:
          VITE_PROD_API_URL: http://${{ secrets.PUBLIC_IP }}:3000
          VITE_NODE_ENV: production
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/qualty-web:latest

  deploy:
    needs: pushing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: appleboy/ssh-action@v1.0.0
      name: Remove qualty_web container
      with:
        host: ${{ secrets.PUBLIC_IP }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        script: docker rm -f qualty_web

    - uses: chaplyk/docker-compose-remote-action@v1.1
      name: Docker-Stack Remote Deployment
      with:
        ssh_host: ${{ secrets.PUBLIC_IP }}
        ssh_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        ssh_user: ${{ secrets.DEPLOY_USERNAME }}
        compose_file: docker-compose.yaml
        service: web
        pull: true
      